# Generated by Django 5.2.4 on 2025-08-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_alter_orderitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='categories/default.PNG', upload_to='categories/'),
        ),
    ]
