# Generated by Django 5.2.4 on 2025-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_alter_category_options_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='Customer ID'),
        ),
    ]
